### ISSUE TITLE
If event is one day, maybe event end data should be set equal to event start date for purposes of popup graphs

### ISSUE THREAD

**Issue by marsmith** [USGS-WiM/FEV#107]
After I wrote this, I realized this will not apply for CURRENT events, where you'd want to see the graph until the current time.  so perhaps a quick check if the event is greater than a week ago, then do what suggested below?

This happens here:
https://github.com/USGS-WiM/FEV/blob/master/src/scripts/query.js#L770-L773
and here:
https://github.com/USGS-WiM/FEV/blob/master/src/scripts/query.js#L674-L678

propose : 

```
    if (fev.vars.currentEventActive == true && fev.vars.currentEventEndDate_str == '') {
        fev.vars.currentEventEndDate_str = fev.vars.currentEventStartDate_str 
    }
```

**Comment by BlakeDraper** [comment]
Email out to Todd Koenig for this thoughts on the bad data situation.
