### ISSUE TITLE
Grey out NWIS Gages layer when it won't load due to zoom level

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/FEV#122]
To help the user realize that it won't load when zoomed out too far.

**Comment by HansVraga** [comment]
This came up during the storm team call that users thought they were waiting for it to load when zoomed too far out.

**Comment by BlakeDraper** [comment]
Not graying out, but inserted more prevalent and dynamic message. Still not ideal - I'm open to ideas though. Closing for now. PR #139
