### ISSUE TITLE
Handle GeoJson points with bad lat/long values.

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/FEV#123]
A yet undetermined method of data entry allowed a user to insert the text "NaN" as lat/long values in a site, which a created HWM inherited. This broke display of ALL HWMs for the event in question (Matthew). Even as we look to prevent that sort of text entry in the future for STNWeb, we should look into handling that more gracefully on the FEV side of the house.

**Comment by BlakeDraper** [comment]
Implemented with PR #126
