### ISSUE TITLE
Implement SSL/https

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/FEV#129]
TX has their Geosearch working on https://
but it sounds like parts of it doesn't work...

> You may already know this, but USGS water services and all of NWISWeb for that matter doesn't seem to be https yet.
> So our clientside stuff accessing NWISWeb water services all broke.
> They have a https staging area while they are transitioning that solved our problem.
> Put "staging" in normal NWISWeb urls to access, examples:
> https://staging.waterservices.usgs.gov/
> https://staging.waterdata.usgs.gov/tx/nwis/uv/?site_no=08123620&PARAmeter_cd=00065,00060,00054,62614,62615,62619,63158,63160
> I'm assuming this is a temp measure and at some point hopefully soon the "staging" can be dropped, like
> https://waterservices.usgs.gov/
> 
> Good luck.

**Comment by BlakeDraper** [comment]
Going to wait on this until the NWIS stuff is all https - currently if it aint broke don't fix it, and I think if we start messing with these URLs, things will become fragile.

**Comment by BlakeDraper** [comment]
TX Search find to use https - sez Marty

**Comment by BlakeDraper** [comment]
This is done with PR #139. Cloudfront caching on the test.wim.usgs.gov domain preventing successful test at the moment but I think this is done. Will confirm tomorrow after I have time to clear cloudfront cache. Caveat emptor for using cloudfront for test env. Should prob just get a linux machine with its own cert for this purpose.

**Comment by BlakeDraper** [comment]
Done with PR #143
