### ISSUE TITLE
CORS issue with NWIS retrieval

### ISSUE THREAD

**Issue by BlakeDraper** [USGS-WiM/FEV#138]
This is a sudden development, But need to to update the requests to URLs to https anyway, which may involve switching domains anyway, depending on where NWIS is at on the https front anyway.

**Comment by marsmith** [comment]
I just saw this come up in slack.  NWIS is fully- ssl enabled as far as I know, I've updated to https in a couple projs.  see if that fixes this I guess? It may be doing a http -> https redirect right now that is causing the CORS

**Comment by BlakeDraper** [comment]
Oh yeah looks like you are right. Cool, I thought I was going to have to sub in that alternate domain David Coyle shared with us that one time.

**Comment by BlakeDraper** [comment]
Done with PR #139
