### ISSUE TITLE
Invalid search terms persist in GEOSEARCH when clicking X or close in the modal

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/FEV#152]
Not really sure if this is an actual issue or not, so feel free to delete this if it's not.

I noticed that if the user hits "enter" or clicks the tip, the software finds the closest thing to their search term. Clicking the "Go!" button doesn't do anything-- I might expect it to do the same thing as hitting "enter" or the tip text.

Clicking the X or Close button returns the user to the map. When they click GEOSEARCH again, their bad search term is still there.

**Steps to reproduce:**
1. go to http://test.wim.usgs.gov/FEV and select any event.
2. click the GEOSEARCH button in the top right corner of the screen
3. enter invalid search terms (e.g. "12345 home st. richmond, va")
4. Click "Go!" - note: nothing happens
5. Click the "X" or Close button in the modal.
6. Click the GEOSEARCH button again.
7. note that the invalid search term is still present.

**Comment by BlakeDraper** [comment]
You are right, this is an issue. Also I have just realized that this Texas geosearch engine (made by some USGS guys at the Texas Water Science Center) does not actually respect address-level geocoding. Not necessarily a deal-breaker but generally something that people expect.

**Comment by HansVraga** [comment]
This should be corrected as part of #166
