### ISSUE TITLE
Remove "www" from WiM button's address "https://www.wim.usgs.gov/" in "About the Application" modal

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/FEV#153]
See image for ![image](https://cloud.githubusercontent.com/assets/23640741/21934075/0df0b6c2-d976-11e6-8539-2c56722c1cc1.png)

**Comment by BlakeDraper** [comment]
Good call. :+1:

**Comment by BlakeDraper** [comment]
Done with PR #161
