### ISSUE TITLE
Layering Symbol display - RDGs and Real-time Stream Gages

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/FEV#175]
Switch which of these are "on top" - RDGs should show up above Real-time Stream Gages when both layers are selected. See image for example of what currently happens (example is event-Harvey)

![image](https://user-images.githubusercontent.com/12058013/31408485-c16c1388-add6-11e7-85ed-648c70715437.png)

**Comment by tkoenigusgs** [comment]
In addition, can we make the realtime streamgages show up in the multi-icon fan thingy that happens when multiple icons are showing in the same space?  Then the user can pick which one they intended to view.

**Comment by HansVraga** [comment]
The above comment covered in: https://github.com/USGS-WiM/FEV/issues/206
