### ISSUE TITLE
Add link to STN Data Dictionary

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/FEV#186]
See this ticket for recent activity surrounding the data dictionary https://github.com/USGS-WiM/STNWeb/issues/424

We need to figure out where to place it in STN.

Maybe in the Get Data section of the sidebar underneath the "STN Data Portal" mention?

**Comment by HansVraga** [comment]
Maybe here, with a link?
Or we could do a smaller footnote in a seperate <p> </p> or <div>
![image](https://user-images.githubusercontent.com/12058013/41373785-505ed526-6f1f-11e8-874b-d7c2b9411459.png)

**Comment by lprivette** [comment]
Added to About Modal and Get Data section of sidebar
