### ISSUE TITLE
Using wrong endpoint for sensor 'get data'

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/FEV#187]
Get Data for Hurricane Harvey will hit this endpoint: https://stn.wim.usgs.gov/STNServices/Instruments.json?Event=180&States=&County=&SensorType=&CurrentStatus=&CollectionCondition=&DeploymentType=

which is the endpoint for returning all of the sensors. We should be hitting:

https://stn.wim.usgs.gov/STNServices/Instruments/FilteredInstruments.json?Event=180&EventType=&EventStatus=&States=&County=&CurrentStatus=&CollectionCondition=&SensorType=&DeploymentType=

**Comment by HansVraga** [comment]
https://github.com/USGS-WiM/STNServices2/issues/135

**Comment by lprivette** [comment]
Is there anyone I need to let know that we fixed this or was this just something you noticed @HansVraga

**Comment by HansVraga** [comment]
But let Todd know this was found and corrected.

**Comment by HansVraga** [comment]
Something I noticed.

_________________________________


*Hans Vraga*Project Manager | 703.648.5670
Web Informatics and Mapping (WIM) <https://wim.usgs.gov/>
United States Geological Survey
USGS National Center | Office 5A133
