### ISSUE TITLE
Mock-up possibilities for National View

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/FEV#190]
Our goal is to provide a "national view" for both the splash screen and for when a user clears all filters from FEV. We want to communicate the number and extent of Events where data has been gathered without overloading the user. Ideas for how this can be shared here. This issue is complete when we decide on an initial direction for the national view.

**Comment by HansVraga** [comment]
@jknewson suggested taking a look at the sidebar interface on https://test.wim.usgs.gov/groundwaterwatch/ to show multiple national views based on categories.

**Comment by HansVraga** [comment]
Previously discussed ideas include showing a national view with icons for each event. Clicking the Icon could show a pop-up with basic event information and highlight HUCs or Counties where data was gathered as part of that event.

**Comment by jknewson** [comment]
Something similar to https://coast.noaa.gov/hurricanes/ historical hurricane tracks for each event in STN.
ie: all historic storm tracks are loaded onto map, using filters (or selecting event) will populate all (instruments/hwms etc)

**Comment by lprivette** [comment]
use first site's lat/long in event as event's lat/long in flatfile for mockup
