### ISSUE TITLE
Match Streamgage pop-up reference to NWISWeb to Rain gage

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/FEV#208]
Add the following text prior to the link to NWIS in the pop-up
>Gage Height data courtesy of the U.S. Geological Survey

Then the link to NWISWeb

**Comment by lprivette** [comment]
so this would go in here in both real-time and rain gages? 
![image](https://user-images.githubusercontent.com/23640741/86625909-e61d5080-bf93-11ea-9418-f4b7fd3ed7e7.png)
