### ISSUE TITLE
Improve visibility of Rain/stream gage layer requirements

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/FEV#209]
Users continue to not understand they need to zoom in to see streamgages and rain gages.

If one of those layers are checked on and the user is not zoomed in far enough, flash the message in the Legend explaining they need to zoom to a particular level.

If that isn't very straightforward, use a toast notification, or add a notification that looks like the "loading" notification currently in the system (see screenshot).

![image](https://user-images.githubusercontent.com/12058013/47034859-7c696d00-d146-11e8-8886-f4b07b0320e5.png)

**Comment by lprivette** [comment]
disable checkbox if users are zoomed too far out
