### ISSUE TITLE
Add STNWeb Public info to FEV

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/FEV#212]
Retire STNWeb Public HWM/Sensor pages in favor of replacing the functionality in FEV. Add an expandable pop-up to view all the info or perhaps a modal that could be opened for more info.

- [x] include feature to Direct link to HWM/Sensor (share) (marked off here in favor of distinct issue #277 ) 
- [x] Photos & expanded (public) info

**Comment by lprivette** [comment]
![image](https://user-images.githubusercontent.com/23640741/93793779-47ed6e00-fc05-11ea-9514-f279d4dc4511.png)
need to do for HWM data pages

**Comment by BlakeDraper** [comment]
I have submitted PR #270, but just noticed Hans requested the link for sharing. So does that mean just the link to the existing public data page?

**Comment by HansVraga** [comment]
Let's chat about this in the next check-in?
