### ISSUE TITLE
Create separate layer for tidal gages

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/FEV#219]
Tidal gages are currently included under stream gages. Suggestion is to pull those out and make its own layer. See user request below for more info:

added to the stn user group spreadsheet.

> No they are lumped into the streamgage category on FEV. The codes being used for tidal stations in NWIS are:
> 62619	Physical	Estuary or ocean water surface elevation above NGVD 1929, feet	
> 62620	Physical	Estuary or ocean water surface elevation above NAVD 1988, feet
> Since you are already pulling these sites in FEV could they be separated into a new category for Real-Time Tidal Gages if there is agreement. I don't remember why they were lumped in the past, but there was some reason for it at the time, maybe Marie or Robert would remember. But if it can be done I feel it would be a useful addition.

**Comment by HansVraga** [comment]
Duplicate, closing
