### ISSUE TITLE
Add pop-up for IE prompting user to use a modern browser

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/FEV#222]
The site doesnt' load for me in IE. Rather than chase IE's ghosts, let's direct users to use a modern web browser. Here is an example pop-up that you see when someone tries to access the new sparrow pages, something like this would do:

![image](https://user-images.githubusercontent.com/12058013/73669044-70235f00-466c-11ea-96a8-b506a12571b2.png)

https://stn.wim.usgs.gov/fev/

**Comment by BlakeDraper** [comment]
See the GLCWRA family for the code and a read-made popup you could use for this. 

![image](https://user-images.githubusercontent.com/6978380/73669311-d7d9aa00-466c-11ea-808e-605f5e1cdc9d.png)
