### ISSUE TITLE
Allow multiple events to be displayed

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/FEV#228]
> Would be great to be zoomed in to area of interest and toggle between different events for different data types (sensors, HWMs, peaks, etc) such that 1 or more events could be displayed separately or together at the same time. Need this capability without having FEV being refreshed at start over mode. If needed, maybe this could be an internal side only.

For this first stab at implementing this lets figure out how to setup for 2 events and see how that runs.

If markers are struggling, we could try to implement those clusters that kathy setup in STNWeb2. This may be difficult though with spiderfy.

Things to think about: How to indicate which site belongs to which event. We'd include the event in name in the popup, but I wonder about adding like different color halos behind the icons or something. Something to visually indicate. but maybe that's not even necessary. Open to others thoughts on this.

**Comment by kathymd** [comment]
I assume we ultimately decided not to include this feature, so I'm closing this issue. However, I did get a multi-event modal working, and if anyone wants to use that code in the future, you can find it on the `multiEventModal` branch.
