### ISSUE TITLE
Break up real-time gages into tidal and stream gages

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/FEV#230]
> FEV: Create separate layer for tidal gages from stream gages

**Comment by HansVraga** [comment]
Helpful info in #219

**Comment by lprivette** [comment]
From the stn user group it sounded like they thought the tidal gages are included in the current real time gages, but the parameter codes used contain no tidal specific one so there may be a misconception here.

Here we have tidal codes: https://help.waterdata.usgs.gov/parameter_cd?group_cd=PHY. 72276 (tidal water level)

when using https://waterservices.usgs.gov/rest/IV-Test-Tool.html to test and see if any tidal gages are present I came up with none. Example test url searching entirety of Florida https://waterservices.usgs.gov/nwis/iv/?format=waterml,2.0&stateCd=fl&parameterCd=72276&siteType=OC,OC-CO,ES,LK,ST,ST-CA,ST-DCH,ST-TS&siteStatus=all

Is it possible that this code is/was never used? We should bring this up at the next stn user group meeting

**Comment by lprivette** [comment]
https://waterservices.usgs.gov/nwis/iv/?format=waterml,2.0&stateCd=ny&parameterCd=62619&siteType=OC,OC-CO,ES,LK,ST,ST-CA,ST-DCH,ST-TS&siteStatus=all

62619 - older datum (don't use? or show both and reference datum in popup)
62620
