### ISSUE TITLE
Investigate adding SOFAR buoys 

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/FEV#331]
API access given by Isabel and Tim with Sofar

**Comment by lprivette** [comment]
Attempted to use AWS Secrets Manager, but it seems credentials still need to be passed so this will not be a solution. https://aws.amazon.com/secrets-manager/

**Comment by lprivette** [comment]
Spoke with Aaron who determined a reverse-proxy to mask the requests to sofar can work here. 

I emailed Athena and the Sofar team telling them of our solution, asking them if they had any other ideas, and telling that it would probably take sysops time to implement this solution. Waiting for their response now. 

If we move forward with this Aaron had the idea to write a python script running in CGI mode.

**Comment by aaronstephenson** [comment]
I have written a working reverse proxy python cgi script in a new branch and PR (#332) and deployed it to a server for testing.
