### ISSUE TITLE
Reduce number of decimal places in Peak Summary labels

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/FEV#339]
Peak Summary labels are currently showing 6 decimal places. Athena and Kevin Grimsley have requested that it be reduced to 2 decimal places.

example at 30.5105, -81.4608
![image](https://user-images.githubusercontent.com/40237491/194125126-76a935a5-9468-4845-aee4-87401716532a.png)

Note: WaveLab will be updated later to output the correct level of precision.

**Comment by amedenblik** [comment]
I can't get FEV running on my machine, but I think this might fix it?

Change `toString()` to `toFixed(2)` on this line: https://github.com/USGS-WiM/FEV/blob/dev/src/scripts/core.js#L1524

**Comment by lprivette** [comment]
Done in prod
